services:
  server:
    container_name: dailiestask-server
    build:
      context: ./server
      target: ${NODE_ENV:?}
    ports:
      - ${PORT:?}:${PORT:?}
    volumes:
      - ./server/src:/home/node/app/src
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - DATABASE_URL=${DATABASE_URL:?}
      - DEV_DATABASE_URL=${DEV_DATABASE_URL:?}
      - PORT=${PORT:?}
      - NODE_ENV=${NODE_ENV:?}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET:?}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET:?}
      - WEB_URL=${WEB_URL:?}
  db:
    profiles: [dev]
    image: postgres
    restart: always
    ports:
      - "5434:5434"
    expose:
      - 5434
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    volumes:
      - db-data:/var/lib/postgresql/data
    command: ["postgres", "-p", "5434"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:?} -d ${POSTGRES_DB:?} -p 5434",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-data: