services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_dev
    ports:
      - "5435:5435"
    expose:
      - 5435
    volumes:
      - /var/lib/postgresql/data
    command: ["postgres", "-p", "5435"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U -p 5435",
        ]
      interval: 5s
      timeout: 5s
      retries: 5